### ISSUE TITLE
decode blend

### ISSUE THREAD

**Issue by adam-aok** [MiniKimmy/sketchfab_download#1]
Step 2 --decode blend-- I am receiving the error: 
"The application has failed to start because its side-by-side configuration is incorrect. "

**Comment by MiniKimmy** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/the-application-has-failed-to-start-because-the/5c6a015e-4162-491d-b7d9-f3b13612e304
------------
You can take a try.

**Comment by MiniKimmy** [comment]
> Step 2 --decode blend-- I am receiving the error:
> "The application has failed to start because its side-by-side configuration is incorrect. "

https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/the-application-has-failed-to-start-because-the/5c6a015e-4162-491d-b7d9-f3b13612e304
You can take a try.

**Comment by adam-aok** [comment]
ERROR: Cannot resolve reference Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8".
The issue appears to be with Blender. 
I get this image when I attempt to open blender as well. Would it be possible to make this run with other copies of blender
![image](https://user-images.githubusercontent.com/50712829/108316932-9179bf00-718b-11eb-882e-f4d0b7355be0.png)

**Comment by MiniKimmy** [comment]
> ```
> ERROR: Cannot resolve reference Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8".
> ```
> 
> The issue appears to be with Blender.
> I get this image when I attempt to open blender as well. Would it be possible to make this run with other copies of blender
> ![image](https://user-images.githubusercontent.com/50712829/108316932-9179bf00-718b-11eb-882e-f4d0b7355be0.png)
--------------------------------
https://answers.microsoft.com/en-us/windows/forum/all/the-application-has-failed-to-start-because-its/ef9b01d5-3c18-479e-bf71-a9c28123c807

You need to install a dependence called "Microsoft.VC90.OpenMP"  which can download from Microsoft Website.

"Microsoft.VC90.OpenMP" can be downloaded from the following redistributable packages ：
1）Microsoft Visual C++ 2010 Redistributable Package (x86) 
2）Microsoft Visual C++ 2008 Redistributable Package (x86)

**Comment by adam-aok** [comment]
That fixed it! I was missing the x64 versions. Executes perfectly now. Thank you!
